# Webserv 프로젝트
## 진척 사항

- socket 통신 구현
- non-blocking 적용
- kqueue 적용
- Server, ConnectionHandler, EventLoop 클래스로 분리 리팩토링 중
  - 커넥션이 끊어지는 오류 발생
  - 처음 연결은 잘 되는데, read 이벤트를 감지하지 못하는 오류 발생 중

## explict 키워드
**참고 자료**

[explicit specifier](https://en.cppreference.com/w/cpp/language/explicit)

[C++ explicit 키워드 이해하기](https://dydtjr1128.github.io/cpp/2019/07/13/Cpp-explicit-keyowrd.html)

```c++
class ServerException : public std::exception {
   public:
    explicit ServerException(const std::string& message);
}
```

- 자신이 원하지 않는 형변환이 일어나지 않도록 제한하는 키워드
- 주로 단일 파라미터를 받는 생성자에 사용한다.

```c++
void foo(ServerException e);

foo("An error occurred");  // 암시적으로 std::string에서 ServerException으로 변환
```

- `explict`를 사용하지 않은 경우 컴파일러가 자동으로 타입을 추론해 암시적 형변환을 수행한다.
- 예상치 못한 오류가 발생할 수 있다.

```c++
void foo(ServerException e);

foo("An error occurred"); // compile error
foo(ServerException("An error occurred"));  // 명시적 변환 필요
```

- `explict`를 사용한 경우 반드시 명시적으로 형변환을 해줘야 한다.

## custom exception error
**참고 자료**

[stack overflow](https://stackoverflow.com/questions/53829852/exception-specification-of-overriding-function-is-more-lax-than-base-version)

[std::unexpected](https://en.cppreference.com/w/cpp/error/unexpected)

### 문제 상황
```c++
class ServerException : public std::exception {
   public:
    explicit ServerException(const std::string& message);

    virtual const char* what() const throw();

   private:
    std::string msg;
  };
```

- 사용자 정의 `exception`을 제작하는 도중 아래와 같은 에러가 발생하였다.

```
In file included from Server.cpp:1:
./Server.hpp:26:9: error: exception specification of overriding function is more lax than base version
  class ServerException : public std::exception {
        ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/exception:101:13: note: overridden virtual function is here
    virtual ~exception() _NOEXCEPT;
            ^
1 error generated.
make: *** [Server.o] Error 1
```

- "overriding 하는 함수의 범위가 base 함수의 범위보다 널널하다"라는 오류의 내용이다.

### std::exception
```c++
#if !defined(_LIBCPP_ABI_VCRUNTIME)
class _LIBCPP_EXCEPTION_ABI exception
{
public:
    _LIBCPP_INLINE_VISIBILITY exception() _NOEXCEPT {}
    virtual ~exception() _NOEXCEPT;
    virtual const char* what() const _NOEXCEPT;
};
```

- c++ 라이브러리에 정의된 `std::exception` 클래스다.
- 생성자, 소멸자, what() 메서드에 모두 `noexcept` 키워드가 붙어있다.

### noexcept vs throw()
- `noexcept` 키워드는 c++11에서 새로 정의된 키워드이다.
- 해당 함수가 예외를 발생하지 않음을 명시한다.
- c++11 이전에는 `throw()` 키워드를 사용하였다.
  - 기본적으로 `throw(예외명)`처럼 사용한다.
  - `throw()`는 던져지는 예외가 없다는 뜻
- `throw()`는 강력한 도구가 아니었다.
  - `throw()`가 붙은 함수가 예외를 발생시킨다면 `std::unexpected`를 호출하는 것이 전부였다.
  - 반면 `noexcept`가 붙은 함수가 예외를 발생시킨다면 프로그램을 즉시 종료한다.
- `throw()`보다 명시적으로 의미를 전달하기 위해 `noexcept` 키워드를 도입한 것 같다.

### 문제 분석
- 오류 로그를 보면 `virtual ~exception() _NOEXCEPT;` 라는 부분에서 예외가 발생하였다.
- 나는 새로 제작한 예외 클래스에서 소멸자를 선언하지 않았고, 이로 인해 컴파일러가 기본 소멸자를 넣어줬을 것이다.
  - c++11 이후에는 기본 소멸자에 `noexcept`가 기본으로 적용된다.
  - c++11 이전에는 이와 같은 장치가 없어 오류가 발생한 것이다.
- base 클래스에서는 소멸자에 `noexcept` 키워드가 있었으나, derived 클래스에는 키워드가 명시되어 있지 않았다.
- c++ 표준에 따라 가상 함수가 `non-throwing`하다면, 이를 `overriding`하는 함수 또한 `non-throwing` 해야 한다.

> 18.4 Exception speciﬁcations [except.spec]
> 
> ...
>
> If a virtual function has a non-throwing exception speciﬁcation, all declarations, including the deﬁnition, of any function that overrides that virtual function in any derived class shall have a non-throwing exception speciﬁcation, unless the overriding function is deﬁned as deleted.

### 문제 해결
```c++
class ServerException : public std::exception {
   public:
    explicit ServerException(const std::string& message);
    ~ServerException(void) throw();

    virtual const char* what() const throw();

   private:
    std::string msg;
  };
```
- 컴파일러가 기본 소멸자를 추가하지 않도록 소멸자를 명시하였다.
- `throw()` 키워드를 붙여 c++ 표준에 맞게 `non-throwing` 하도록 하였다.

# 운영체제 스터디
## 질문 정리
- os와 kernel의 차이가 정확히 무엇일까?
- concurrency와 pallelelism의 차이는 무엇일까?
- VMM은 OS위에 존재하는 프로그램일까? 아니면 OS와 같은 단에 위치하는 프로그램일까?
- register는 뭘까?
- Text, Data, Heap, Stack 영역이 각각 담당하는 건 뭘까?
- Interrupt가 정확히 뭘까?
